language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - jsonfs
# command to run tests
script:
  - python -m unittest discover
notifications:
  - lchan1994@yahoo.com
